services:
  mysql:
    container_name: mysql
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ocrpassword
      MYSQL_USER: ghostuser
      MYSQL_PASSWORD: ocrpassword
      MYSQL_DATABASE: ghost
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  blog:
    build: https://github.com/OpenClassrooms-Student-Center/ghost-cms.git
    depends_on: 
      mysql:
        condition: service_healthy
    ports:
      - 2368:2368
    environment:
      NODE_ENV: production
version: '2.1'
