version: '3'

services:
        db:
          image: mysql:5.7
          volumes:
                  - db_data:/var/lib/mysql
          restart: always
          environment:
                  MYSQL_ROOT_PASSWORD: ocrpassword
                  MYSQL_DATABASE: ghost
                  MYSQL_USER: ghostuser
                  MYSQL_PASSWORD: ocrpassword

        ghost:
                depends_on:
                        - db
                image: ghost:1-alpine
                restart: always
                ports:
                        - "8080:2368"
                environment:
                        database__client: mysql
                        database__connection__host: db
                        database__connection__user: ghostuser
                        database__connection__password: ocrpassword
                        database__connection__database: ghost
                        NODE_ENV: production 
volumes:
  db_data: {}
